
name: 'StandardRB linter'
description: 'A GitHub Action to run StandardRB linters against Ruby and Rails code.'
author: 'Kevin McPhillips <github@kevinmcphillips.ca>'
runs:
  using: 'docker'
  image: 'Dockerfile'
env:
  GITHUB_TOKEN: secrets.GITHUB_TOKEN
branding:
  icon: 'code'
  color: 'gray-dark'
