name: StandardRB

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  standardrb:
    name: StandardRB Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2
        bundler-cache: true
    - name: Bundle
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Run standardrb
      run: bin/standardrb
